version: '3.7'

services: 
  frontend:
    image: frontend-react
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    # [인증서 파일 저장 경로]:/var/www/html
    volumes:
      - /home/ubuntu/docker-volume/ssl2:/var/www/html
    container_name: "frontend"

  backend:
    image: backend-nodejs
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/docker-volume/ssl2:/var/www/html
      - /home/ubuntu/backlog:/usr/app/logs
    container_name: "backend"
    hostname: "backend"
